# CariML Capabilities - Customer Segmentation 
This notebook aims at analyzing the content of an E-commerce database that lists purchases made by âˆ¼4000 customers over a period of one year (from 2010/12/01 to 2011/12/09). Based on this analysis, we develop a model that allows for the anticipation of purchases that will be made by a new customer, based off of only the first purchase.

---
<br></br>
# Table Of Contents
**1. Data Cleaning and Preparation**

**2. Exploring the input features**


---

## 1. Data Preparation 
To begin with, we are going to start by importing all of the modules that will be used in this notebook.

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import datetime, nltk, warnings
import matplotlib.cm as cm
import itertools
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn import preprocessing, model_selection, metrics, feature_selection
from sklearn.model_selection import GridSearchCV, learning_curve
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn import neighbors, linear_model, svm, tree, ensemble
from wordcloud import WordCloud, STOPWORDS
from sklearn.ensemble import AdaBoostClassifier
from sklearn.decomposition import PCA
from IPython.display import display, HTML
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode,iplot
init_notebook_mode(connected=True)
warnings.filterwarnings("ignore")
plt.rcParams["patch.force_edgecolor"] = True
plt.style.use('fivethirtyeight')
mpl.rc('patch', edgecolor = 'dimgray', linewidth=1)
%matplotlib inline

Now, we can load the data with `pandas`. Additionally, we do the following: 
* We convert `InvoiceDate` to a `datetime` datatype
* Give some basic information regarding each column datatype
* Determine the number of null values in each column

In [57]:
# -------------- read in our data csv in the form of a data frame ---------------------
df_initial = pd.read_csv('data/data.csv',encoding="ISO-8859-1",
                         dtype={'CustomerID': str,'InvoiceID': str})
print('Dataframe dimensions:', df_initial.shape)

# convert InvoiceDate to a datetime
df_initial['InvoiceDate'] = pd.to_datetime(df_initial['InvoiceDate'])

"""
 Return information on column/feature types and number of null values 
"""
def display_tabular_info():
    tab_info = pd.DataFrame(df_initial.dtypes).T.rename(index={0:'column type'})
    tab_info = tab_info.append(pd.DataFrame(df_initial.isnull().sum())
                               .T.rename(index={0:'number of null values (#)'}))

    tab_info = tab_info.append(pd.DataFrame(df_initial.isnull().sum() / df_initial.shape[0] * 100)
                               .T.rename(index={0: 'Percentage of null values (%)'}))

    # display the tabular information
    display(tab_info)
    
display_tabular_info()    
display(df_initial[:5])

Dataframe dimensions: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
column type,object,object,object,int64,datetime64[ns],float64,object,object
number of null values (#),0,0,1454,0,0,0,135080,0
Percentage of null values (%),0,0,0.268311,0,0,0,24.9267,0

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

### Key Point

From the above tables we see that **~25%** of the entries do not have a `CustomerID`. Without this value and based only on the current available data, we are not able to to impute a `CustomerID`s associated with each entry, so they cannot be utilized going forward. Hence, we will delete them (135,080 in total). This is worth noting because losing 25% of the potential input data will certainly affect prediction quality.

In [58]:
df_initial.dropna(axis = 0, subset = ['CustomerID'], inplace = True)
print("Update DataFrame Dimensions after removing null values: ", df_initial.shape)

# display tabular information after the null values have been removed
display_tabular_info()

Update DataFrame Dimensions after removing null values:  (406829, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
column type,object,object,object,int64,datetime64[ns],float64,object,object
number of null values (#),0,0,0,0,0,0,0,0
Percentage of null values (%),0,0,0,0,0,0,0,0

With that taken care of, the last thing we need to do is check for duplicate entries, and remove them from the dataframe.

In [62]:
print ("Number of duplicate entries: ", df_initial.duplicated().sum()) 
df_initial.drop_duplicates(inplace=True)

Number of duplicate entries:  5225

--- 
<br></br>
## 2. Exploring the Input Features
With our data fully loaded and null values removed, we can begin exploring the different features we have to work with. The dataframe contains a total of 8 variables that correspond to:
> **InvoiceNo**: The invoice number. A nominal 6 digit number uniquely assigned to each transaction. If this value starts with the letter "C", it means that the order was cancelled. <br>
**StockCode**: Product/item code. This is a nominal, 5 digit number that is uniquely assigned to each distinct product <br>
**Description**: Product/item name. This is a string.

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472,Germany
1981,C536548,22077,6 RIBBONS RUSTIC CHARM,-6,2010-12-01 14:33:00,1.65,12472,Germany
1982,C536548,22631,CIRCUS PARADE LUNCH BOX,-1,2010-12-01 14:33:00,1.95,12472,Germany
1983,C536548,22168,ORGANISER WOOD ANTIQUE WHITE,-2,2010-12-01 14:33:00,8.50,12472,Germany
1984,C536548,21218,RED SPOTTY BISCUIT TIN,-3,2010-12-01 14:33:00,3.75,12472,Germany
1985,C536548,20957,PORCELAIN HANGING BELL SMALL,-1,2010-12-01 14:33:00,1.45,12472,Germany
1986,C536548,22580,ADVENT CALENDAR GINGHAM SACK,-4,2010-12-01 14:33:00,5.95,12472,Germany
3170,C536606,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-2,2010-12-02 09:10:00,2.95,14092,United Kingdom
3338,C536622,22752,SET 7 BABUSHKA NESTING BOXES,-2,2010-12-02 10:37:00,8.50,12471,Germany
3410,C536625,22839,3 TIER CAKE TIN GREEN AND CREAM,-2,2010-12-02 10:46:00,14.95,14766,United Kingdom
3693,C536642,21463,MIRRORED DISCO BALL,-1,2010-12-02 11:56:00,5.95,14390,United Kingdom
...,...,...,...,...,...,...,...,...
538564,C581409,82482,WOODEN PICTURE FRAME WHITE FINISH,-1,2011-12-08 14:08:00,2.95,12476,Germany
538565,C581409,22173,METAL 4 HOOK HANGER FRENCH CHATEAU,-2,2011-12-08 14:08:00,3.29,12476,Germany
538566,C581409,85199L,LARGE HANGING IVORY & RED WOOD BIRD,-1,2011-12-08 14:08:00,0.65,12476,Germany
538567,C581409,85127,SMALL SQUARE CUT GLASS CANDLESTICK,-5,2011-12-08 14:08:00,4.95,12476,Germany
540072,C581460,22197,POPCORN HOLDER,-5,2011-12-08 18:48:00,0.72,13078,United Kingdom
540073,C581460,22107,PIZZA PLATE IN BOX,-1,2011-12-08 18:48:00,1.25,13078,United Kingdom
540078,C581462,16219,HOUSE SHAPE PENCIL SHARPENER,-48,2011-12-08 18:51:00,0.06,12985,United Kingdom
540079,C581462,21642,ASSORTED TUTTI FRUTTI PEN,-72,2011-12-08 18:51:00,0.29,12985,United Kingdom
540080,C581463,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,-2,2011-12-08 18:56:00,7.95,17526,United Kingdom
540081,C581464,23458,DOLLY CABINET 3 DRAWERS,-1,2011-12-08 18:57:00,14.95,15951,United Kingdom
540082,C581464,71477,COLOURED GLASS STAR T-LIGHT HOLDER,-6,2011-12-08 18:57:00,3.95,15951,United Kingdom
540083,C581465,23660,HENRIETTA HEN MUG,-2,2011-12-08 18:59:00,1.65,15755,United Kingdom
540084,C581465,22171,3 HOOK PHOTO SHELF ANTIQUE WHITE,-1,2011-12-08 18:59:00,8.50,15755,United Kingdom
540085,C581465,21876,POTTERING MUG,-4,2011-12-08 18:59:00,1.65,15755,United Kingdom
540086,C581465,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-3,2011-12-08 18:59:00,2.95,15755,United Kingdom
540087,C581466,22838,3 TIER CAKE TIN RED AND CREAM,-1,2011-12-08 19:20:00,14.95,13883,United Kingdom
540088,C581466,22720,SET OF 3 CAKE TINS PANTRY DESIGN,-2,2011-12-08 19:20:00,4.95,13883,United Kingdom
540089,C581466,21216,"SET 3 RETROSPOT TEA,COFFEE,SUGAR",-1,2011-12-08 19:20:00,4.95,13883,United Kingdom
540090,C581466,21535,RED RETROSPOT SMALL MILK JUG,-2,2011-12-08 19:20:00,2.55,13883,United Kingdom
540091,C581466,21232,STRAWBERRY CERAMIC TRINKET POT,-1,2011-12-08 19:20:00,1.25,13883,United Kingdom
540141,C581468,21314,SMALL GLASS HEART TRINKET POT,-10,2011-12-08 19:26:00,2.10,13599,United Kingdom
540142,C581468,22098,BOUDOIR SQUARE TISSUE BOX,-12,2011-12-08 19:26:00,0.39,13599,United Kingdom
540176,C581470,23084,RABBIT NIGHT LIGHT,-4,2011-12-08 19:28:00,2.08,17924,United Kingdom
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446,United Kingdom
540448,C581490,22178,VICTORIAN GLASS HANGING T-LIGHT,-12,2011-12-09 09:57:00,1.95,14397,United Kingdom
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom